### ISSUE TITLE
using splitraster in google colab

### ISSUE THREAD

**Issue by williamlidberg** [cuicaihao/split_raster#1]
When I import io or geo from splitraster in google colab i get this error:

from splitraster import io
  File "<fstring>", line 1
    (crop_size=)
              ^
SyntaxError: invalid syntax

**Comment by cuicaihao** [comment]
> 

Hi @williamlidberg, I think this is because the default google colab python version is in 3.7  which did not support the f-string format.

**Comment by cuicaihao** [comment]
Hi @williamlidberg, I've updated the packages, please try version 0.3.2 by the following code:
```bash
pip install --upgrade splitraster
```

or uninstall the old one and install the latest one (v.0.3.2 on 16-Jan-2022)

```bash
pip uninstall splitraster
pip installer splitraster==0.3.2 
```

**Comment by williamlidberg** [comment]
Hello, I can confirm that it works now. Thank you for your help!
